# Default values for ml-core-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app_portal_base_url: https://staging.sunbirded.org
application_env: staging
application_port: "3000"
azure_account_key: 7xfcipyy8ycayrwz+d0nqmtrjhjv5rc7mqjlboqhg58+bx2zvylwqtptlwbvokel9f0nga2frtxd1vnrtwpuxa==
azure_account_name: sunbirdstagingpublic
azure_storage_container: samiksha
cloud_storage: azure
elasticsearch_communications_on_off: "off"
elasticsearch_entities_index: ""
elasticsearch_host_url: ""
enable_console_logging: "off"
gotenberg_service_url: http://gotenberg-service:3000
internal_access_token: e7220b7539363210ed15
keycloak_public_key_path: keycloak-public-keys
ml_project_service_url: http://ml-projects-service:3000
ml_survey_service_url: http://ml-survey-service:3000
mongodb_url: mongodb://11.3.2.26:27017/ml-survey
user_service_url: http://learner-service:9000



replicaCount: 1
dockerhub: docker.io
repository: tsprasath91/ml-core-service
image_tag: release-5.2.0_1159b45_4

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

network:
  port: 3000
  targetport: 3000

#ingress:
 # enabled: false
 # className: ""
 # annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  #hosts:
   # - host: chart-example.local
    #  paths:
     #   - path: /
      #    pathType: ImplementationSpecific
 # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

resources:
 limits:
  cpu: 100
  memory: 128Mi
 requests:
  cpu: 100m
  memory: 128Mi

strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

autoscaling:
 enabled: false
 minReplicas: 1
 maxReplicas: 100
 targetCPUUtilizationPercentage: 80
 targetMemoryUtilizationPercentage: 80

#nodeSelector: {}

#tolerations: []

#affinity: {}


