apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name}}-config
  namespace: {{ .Release.Namespace }}
data:
  APPLICATION_ENV: "{{ .Values.application_env }}"
  APPLICATION_PORT: "{{ .Values.application_port }}"
  APP_PORTAL_BASE_URL: "{{ .Values.app_portal_base_url }}"
  AZURE_ACCOUNT_KEY: "{{ .Values.azure_account_key }}"
  AZURE_ACCOUNT_NAME: "{{ .Values.azure_account_name }}"
  AZURE_STORAGE_CONTAINER: "{{ .Values.azure_storage_container }}"
  CLOUD_STORAGE: "{{ .Values.cloud_storage }}"
  GOTENBERG_SERVICE_URL: "{{ .Values.gotenberg_service_url }}"
  INTERNAL_ACCESS_TOKEN: "{{ .Values.internal_access_token }}"
  KEYCLOAK_PUBLIC_KEY_PATH: "{{ .Values.keycloak_public_key_path }}"
  ML_PROJECT_SERVICE_URL: "{{ .Values.ml_project_service_url }}"
  ML_SURVEY_SERVICE_URL: "{{ .Values.ml_survey_service_url }}"
  MONGODB_URL: "{{ .Values.mongodb_url }}"
  USER_SERVICE_URL: "{{ .Values.user_service_url }}"